/*
 * generated by Xtext
 */
package org.gololang.gldt.core.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GoloUiModule extends org.gololang.gldt.core.ui.AbstractGoloUiModule {
	public GoloUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
