/*
 * generated by Xtext
 */
package org.gololang.gldt.core.ui.contentassist

import org.gololang.gldt.core.ui.contentassist.AbstractGoloProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class GoloProposalProvider extends AbstractGoloProposalProvider {
}
