/*
* generated by Xtext
*/
package org.gololang.gldt.core;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GoloStandaloneSetup extends GoloStandaloneSetupGenerated{

	public static void doSetup() {
		new GoloStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

