/*
 * generated by Xtext
 */
package org.gololang.gldt.core;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GoloRuntimeModule extends org.gololang.gldt.core.AbstractGoloRuntimeModule {

}
